ALTER TABLE shops ADD COLUMN IF NOT EXISTS primary_color VARCHAR(20) NOT NULL DEFAULT '#f97316';
ALTER TABLE shops ADD COLUMN IF NOT EXISTS business_registration_number VARCHAR(100);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS verification_status VARCHAR(20) NOT NULL DEFAULT 'PENDING'
    CHECK (verification_status IN ('PENDING', 'SUBMITTED', 'VERIFIED', 'REJECTED'));
